services:
  - type: web
    name: customer-feedback-polaris-webhook
    env: node
    plan: free
    branch: production
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: '18'
      - key: ATLASSIAN_ACCESS_TOKEN
        sync: false
      - key: ATLASSIAN_CLOUD_ID
        sync: false
      - key: DEFAULT_INSIGHT_SOURCE
        sync: false
      - key: WEBHOOK_SHARED_SECRET
        sync: false
